# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('is_sharp', models.BooleanField(default=0)),
                ('sharp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chordbuilder.Note')),
            ],
        ),
    ]
