# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chordbuilder', '0002_auto_20160224_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='sharp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chordbuilder.Note'),
        ),
    ]
