# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chordbuilder', '0003_auto_20160224_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModeInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chordbuilder.Interval')),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScaleInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chordbuilder.Interval')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chordbuilder.Scale')),
            ],
        ),
        migrations.AddField(
            model_name='modeinterval',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chordbuilder.Scale'),
        ),
    ]
