# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chordbuilder', '0004_auto_20160301_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='short',
            field=models.CharField(default=b'', max_length=2),
        ),
    ]
