# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chordbuilder', '0005_interval_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeinterval',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='modeinterval',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='scaleinterval',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='scaleinterval',
            name='scale',
        ),
        migrations.DeleteModel(
            name='ModeInterval',
        ),
        migrations.DeleteModel(
            name='ScaleInterval',
        ),
    ]
