# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chordbuilder', '0007_modeinterval_scaleinterval'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='mode',
            name='intervals',
            field=models.ManyToManyField(through='chordbuilder.ModeInterval', to='chordbuilder.Interval'),
        ),
        migrations.AddField(
            model_name='scale',
            name='intervals',
            field=models.ManyToManyField(through='chordbuilder.ScaleInterval', to='chordbuilder.Interval'),
        ),
        migrations.AddField(
            model_name='interval',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chordbuilder.IntervalTypes'),
        ),
    ]
