# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chordbuilder', '0008_auto_20160302_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntervalTypes',
            new_name='IntervalType',
        ),
    ]
